apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        image: solsson/kafka:zookeeper-server-start-2.4.1@sha256:ad92d8e93b369a4c6a9df7b8a198081dfcdcda52e218b1e707b39d63e1897cfb
        args:
        - /etc/kafka/zookeeper.properties.$(POD_NAME)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        image: solsson/kafka:zookeeper-server-start-2.4.1@sha256:ad92d8e93b369a4c6a9df7b8a198081dfcdcda52e218b1e707b39d63e1897cfb
        args:
        - /etc/kafka/zookeeper.properties.$(POD_NAME)
