apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
      - name: broker
        image: solsson/kafka:kafka-server-start-2.4.1@sha256:d7fb916c23fb6a7ad3f9cb9036eb8092a7667e31ce47cee216536566ca35c607
        args:
        - /etc/kafka/server.properties.$(POD_NAME)
