apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
      - name: broker
        image: solsson/kafka:kafka-server-start-2.4.0@sha256:48a80cb0a5600ef5621a4c2c42ceab2c210e52619100a7bfe62f8bd871c38f2a
        args:
        - /etc/kafka/server.properties.$(POD_NAME)
