apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        image: solsson/kafka:zookeeper-server-start-2.4.0@sha256:6037e1b5c103a638ef3e8fdd4c052527afb5cebbf13b005f5309a71fb2354c4e
        args:
        - /etc/kafka/zookeeper.properties.$(POD_NAME)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        image: solsson/kafka:zookeeper-server-start-2.4.0@sha256:6037e1b5c103a638ef3e8fdd4c052527afb5cebbf13b005f5309a71fb2354c4e
        args:
        - /etc/kafka/zookeeper.properties.$(POD_NAME)
